# Generated by Django 6.0.2 on 2026-02-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.practice'),
        ),
    ]
