# Generated by Django 6.0.2 on 2026-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved')], default='submitted', max_length=20),
        ),
    ]
